---
- name: Ldap client
  ansible.builtin.package:
    name:
      - ldap-utils
    state: present

- name: Install AlmaHPC CA Certificate
  copy:
    src: hpcCACert.pem
    dest: /etc/ldap/hpcCACert.pem
    owner: root
    group: root
    mode: '0644'

- name: Configure AlmaHPC ldap client
  ansible.builtin.template:
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: '0644'


