---
- name: Ceph client packages
  ansible.builtin.package:
    name:
      - chrony
    state: present

- name: Ceph main config
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf

