---
- name: /etc/hosts with some common servers/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Italian timezone
  become: yes
  timezone:
    name: "Europe/Rome"
  register: tz
